function(make_interface_lib target_name)
    add_library(${target_name} INTERFACE)
    target_sources(${target_name} INTERFACE ${ARGN})
    add_library(interface::${target_name} ALIAS ${target_name})
    target_include_directories(${target_name} INTERFACE ${CMAKE_CURRENT_SOURCE_DIR})
endfunction()