name: CI-CD Workflow

on:
  push:
    branches:
      - "main"
    tags:
      - "release-*"
  pull_request:
    branches:
      - "main"

env:
  PROJECT_VERSION_PATCH: ${{ github.run_number }}

jobs:
  cache-apt-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Cache apt packages
        id: cache-apt
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: cmake ninja-build g++ valgrind clang-format gcovr
          version: 1.0.0

      - name: Print package-version-list
        run: |
          echo "Cached packages and versions: ${{ steps.cache-apt.outputs.package-version-list }}"
  
      - name: Print all-package-version-list
        run: |
          echo "All cached packages (including dependencies) and versions: ${{ steps.cache-apt.outputs.all-package-version-list }}"

  check-format:
    runs-on: ubuntu-latest
    needs: cache-apt-packages
    steps:
      - name: Restore apt packages from cache
        id: cache-apt
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: cmake ninja-build g++ valgrind clang-format gcovr
          version: 1.0.0

      - name: Install clang-format
        if: steps.cache-apt.outputs.cache-hit != 'true'
        run: sudo apt-get install -y clang-format

      - name: Checkout to repository
        uses: actions/checkout@v4

      - name: Check code formatting
        run: |
          if ! find source -name '*.cpp' -o -name '*.hpp' | xargs clang-format --dry-run --Werror; then
            echo "::error::Code formatting issues were found. Please run 'clang-format' to fix them."
            exit 1
          else
            echo "Code is properly formatted."
          fi

  tests:
    runs-on: ubuntu-latest
    needs: check-format
    strategy:
      matrix:
        preset: [ci-asan, ci-tsan, ci-clang-tidy, valgrind_tests]
    steps:
      - name: Restore apt packages from cache
        id: cache-apt
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: cmake ninja-build g++ valgrind clang-format gcovr
          version: 1.0.0

      - name: Install dependencies
        if: steps.cache-apt.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build g++

      - name: Install Valgrind (only for valgrind_tests)
        if: matrix.preset == 'valgrind_tests' && steps.cache-apt.outputs.cache-hit != 'true'
        run: sudo apt-get install -y valgrind

      - name: Checkout to repository
        uses: actions/checkout@v4

      - name: Sanitizer workflow
        run: cmake --workflow --preset ${{ matrix.preset }}

  build-coverage-report:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Restore apt packages from cache
        id: cache-apt
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: cmake ninja-build g++ valgrind clang-format gcovr
          version: 1.0.0

      - name: Install dependencies
        if: steps.cache-apt.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build g++ gcovr

      - name: Checkout to repository
        uses: actions/checkout@v4

      - name: Coverage workflow
        run: cmake --workflow --preset coverage

      - name: Upload coverage report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: build/coverage/coverage-report/

  release:
    runs-on: ubuntu-latest
    needs: build-coverage-report
    if: startsWith(github.ref, 'refs/tags/release-')

    steps:
    - name: Restore apt packages from cache
      id: cache-apt
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: cmake ninja-build g++ valgrind clang-format gcovr
        version: 1.0.0

    - name: Install dependencies
      if: steps.cache-apt.outputs.cache-hit != 'true'
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build g++

    - name: Checkout to repository
      uses: actions/checkout@v4

    - name: Release workflow
      run: cmake --workflow --preset release

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ env.PROJECT_VERSION_PATCH }}
        draft: false
        prerelease: false

    - name: Upload DEB package to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/release/print_ip-0.0.${{ env.PROJECT_VERSION_PATCH }}-Linux.deb
        asset_name: print_ip-0.0.${{ env.PROJECT_VERSION_PATCH }}-Linux.deb
        asset_content_type: application/vnd.debian.binary-package